export type themeType =
  | 'lucy'
  | 'sunrise'
  | 'blush'
  | 'skyline'
  | 'aura'
  | 'void'
  | 'frost'
  | 'twilight'
  | 'eclipse'
  | 'glow'
  | 'bliss'
  | 'serene'
  | 'shimmer'
  | 'peachy'
  | 'lilac'
  | 'obsidian'
  | 'slate'
  | 'myst'
  | 'midnight'

export type themeColorsType = {
  background: string
  headline: string
  subheadline: string
  foreground: string
  card: string
  cardForeground: string
  popover: string
  popoverForeground: string
  primary: string
  primaryForeground: string
  secondary: string
  secondaryForeground: string
  muted: string
  mutedForeground: string
  accent: string
  accentForeground: string
  destructive: string
  destructiveForeground: string
  border: string
  input: string
  ring: string
  chart1: string
  chart2: string
  chart3: string
  chart4: string
  chart5: string
}
